#!/bin/bash
# hooks/post_checkout
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Unshallowing to get correct tags to work."
# Docker sometimes shallow clones, sometimes does not, so the following command
# may fail.
git fetch --tags --unshallow --quiet origin || true
