# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0018_add_stack_mirrors_and_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'permissions': (('can_administer', 'Can administer projects'), ('can_annotate', 'Can annotate projects'), ('can_browse', 'Can browse projects'), ('can_import', 'Can import into projects'))},
        ),
    ]
