# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:34

from django.db import migrations

forward = """
  UPDATE data_view_type
  SET code_type = 'simple_project_list_data_view',
    title = 'Simple project list view'
  WHERE code_type = 'legacy_project_list_data_view';
"""

backward = """
  UPDATE data_view_type
  SET code_type = 'legacy_project_list_data_view',
    title = 'Legacy project list view'
  WHERE code_type = 'simple_project_list_data_view';
"""

class Migration(migrations.Migration):
    """Update the short name for the Legacy Project List data view to Simple
    Project List.
    """

    dependencies = [
        ('catmaid', '0026_add_additional_stats_indices'),
    ]

    operations = [
        migrations.RunSQL(forward, backward)
    ]
