# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0030_add_sampler_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolatableSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_coordinate', models.FloatField(db_index=True)),
                ('orientation', models.SmallIntegerField(choices=[(0, 'z'), (1, 'y'), (2, 'x')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.Project')),
            ],
            options={
                'db_table': 'interpolatable_section',
            },
        ),
        migrations.RunSQL(
            """
                SELECT create_history_table('interpolatable_section'::regclass);
            """,
            """
                SELECT drop_history_table('interpolatable_section'::regclass)
            """
        )
    ]
