# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 18:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('catmaid', '0047_add_nblast_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCloudGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'pointcloud_group_object_permission',
            },
        ),
        migrations.CreateModel(
            name='PointCloudUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'pointcloud_user_object_permission',
            },
        ),
        migrations.AlterModelOptions(
            name='pointcloud',
            options={'permissions': (('can_read', 'Can read point cloud'), ('can_update', 'Can update point cloud'))},
        ),
        migrations.AddField(
            model_name='pointclouduserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.PointCloud'),
        ),
        migrations.AddField(
            model_name='pointclouduserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='pointclouduserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointcloudgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.PointCloud'),
        ),
        migrations.AddField(
            model_name='pointcloudgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='pointcloudgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
    ]
