# Generated by Django 2.1.3 on 2018-11-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0055_fix_single_node_bug_in_summary_refresh'),
        ('catmaid', '0056_complete_django_auth_user_update'),
    ]

    operations = [
    ]
