# Generated by Django 2.1.5 on 2019-02-01 03:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0061_add_subset_field_to_nblastsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Optional JSON for a stack. Supported is the boolean field "clamp" which can be set to "false" to disable tile access clamping.', null=True),
        ),
        migrations.AlterField(
            model_name='stackmirror',
            name='tile_source_type',
            field=models.IntegerField(choices=[(1, '1: File-based image stack'), (2, '2: Request query-based image stack'), (3, '3: HDF5 via CATMAID backend'), (4, '4: File-based image stack with zoom level directories'), (5, '5: Directory-based image stack'), (6, '6: DVID imageblk voxels'), (7, '7: Render service'), (8, '8: DVID imagetile tiles'), (9, '9: FlixServer tiles'), (10, '10: H2N5 tiles'), (11, '11: N5 volume'), (12, '12: Boss tiles')], default=1, help_text='This represents how the tile data is organized. See <a href="http://catmaid.org/page/tile_sources.html">tile source conventions documentation</a>.'),
        ),
    ]
