# Generated by Django 2.1.8 on 2019-05-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0067_add_groupinactivityperiods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'permissions': (('can_administer', 'Can administer projects'), ('can_annotate', 'Can annotate projects'), ('can_browse', 'Can browse projects'), ('can_import', 'Can import into projects'), ('can_queue_compute_task', 'Can queue resource-intensive tasks'), ('can_annotate_with_token', 'Can annotate project using API token'))},
        ),
    ]
