# Generated by Django 2.1.9 on 2019-06-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0070_remove_pg10_bug_workaround'),
        ('catmaid', '0071_fix_more_location_table_references'),
    ]

    operations = [
    ]
