# Generated by Django 2.2.5 on 2019-10-28 11:32

from django.db import migrations

forward = """
	ALTER TABLE connector_geom ALTER COLUMN id TYPE bigint;
"""

backward = """
	ALTER TABLE connector_geom ALTER COLUMN id TYPE integer;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('catmaid', '0087_add_nblast_normalization_mode'),
    ]

    operations = [
            migrations.RunSQL(forward, backward)
    ]
