# Generated by Django 3.2.10 on 2022-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """This migration DOES NOT change the database, i.e. it doesn't create or
    drop tables. This is due to the "managed = False" definition. These models
    are only proxies used during data export.
    """

    dependencies = [
        ('catmaid', '0118_fix_spatial_notifications_on_node_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReducedInfoUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
