import catmaid.fields
from django.conf import settings
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


forward = """
    CREATE TABLE catmaid_writable_stack (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id int REFERENCES auth_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED NOT NULL,
        project_id int REFERENCES project(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED NOT NULL,
        creation_time timestamptz NOT NULL DEFAULT now(),
        edition_time timestamptz NOT NULL DEFAULT now(),
        stack_id int REFERENCES stack(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED NOT NULL,
        name text NOT NULL,
        path text NOT NULL,
        filetype text DEFAULT 'n5' NOT NULL,
        metadata jsonb DEFAULT '{}' NOT NULL,

        txid bigint DEFAULT txid_current()
    );

    -- Trigger
    CREATE TRIGGER on_edit_writable_stack BEFORE UPDATE ON catmaid_writable_stack
        FOR EACH ROW EXECUTE PROCEDURE on_edit();

    -- History
    SELECT create_history_table('catmaid_writable_stack'::regclass, 'edition_time', 'txid');

    -- Indices
    CREATE INDEX "catmaid_writable_stack_project_id_idx" ON "catmaid_writable_stack" ("project_id");
    CREATE INDEX "catmaid_writable_stack_stack_id_idx" ON "catmaid_writable_stack" ("stack_id");
    CREATE INDEX "catmaid_writable_stack_user_id_idx" ON "catmaid_writable_stack" ("user_id");
"""


backward = """
    SELECT drop_history_table('catmaid_writable_stack'::regclass);

    DROP TABLE catmaid_writable_stack;
"""


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catmaid', '0120_add_can_create_deep_link_permission'),
    ]

    operations = [
        migrations.RunSQL(forward, backward, [
            migrations.CreateModel(
                name='WritableStack',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('creation_time', catmaid.fields.DbDefaultDateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                    ('edition_time', catmaid.fields.DbDefaultDateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                    ('name', models.TextField()),
                    ('path', models.TextField()),
                    ('filetype', models.TextField(default='n5')),
                    ('metadata', models.JSONField(default=dict)),
                    ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.project', related_name='writable_stacks')),
                    ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.stack')),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'catmaid_writable_stack',
                },
            ),
        ]),
    ]
