# Generated by Django 4.2.23 on 2025-10-03 08:45

import catmaid.fields
from django.conf import settings
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catmaid", "0123_update_stack_metadata_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    catmaid.fields.DbDefaultDateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                (
                    "edition_time",
                    catmaid.fields.DbDefaultDateTimeField(
                        default=django.contrib.postgres.functions.TransactionNow
                    ),
                ),
                ("description", models.CharField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("import_log", models.TextField(blank=True, default="")),
                ("import_time", models.FloatField(blank=True, default=0)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="created",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catmaid.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "catmaid_import_task",
            },
        ),
    ]
