# Generated by Django 4.2.30 on 2026-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catmaid", "0124_add_import_task"),
    ]

    operations = [
        migrations.RunSQL(migrations.RunSQL.noop, migrations.RunSQL.noop, [
            migrations.AlterField(
                model_name="brokenslice",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="cardinalityrestriction",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="changerequest",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="class",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="classclass",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="classinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="classinstanceclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="clientdata",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="clientdatastore",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="concept",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="connector",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="connectorclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="connectorgeom",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="datasource",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="dataview",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="dataviewtype",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="deeplink",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="deeplinkstack",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="deeplinkstackgroup",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="dirtynodegridcachecell",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="favoriteproject",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="groupinactivityperiod",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="groupinactivityperiodcontact",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="imagedata",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="importtask",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="interpolatablesection",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="location",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="log",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="message",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="nblastconfig",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="nblastsample",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="nblastsimilarity",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="nodegridcache",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="nodegridcachecell",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="nodequerycache",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="point",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="pointclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="pointcloud",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="pointcloudgroupobjectpermission",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="pointcloudimagedata",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="pointcloudpoint",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="pointclouduserobjectpermission",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="pointconnector",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="pointset",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="project",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="projectstack",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="projecttoken",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="regionofinterest",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="regionofinterestclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="relation",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="relationinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="restriction",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="review",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="reviewerwhitelist",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="sampler",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="samplerconnector",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerconnectorstate",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerdomain",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerdomainend",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerdomaintype",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerinterval",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerintervalstate",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="samplerstate",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="stack",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="stackclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="stackgroup",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="stackgroupclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="stackgrouprelation",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="stackmirror",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="stackstackgroup",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="statssummary",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="suppressedvirtualtreenode",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="textlabel",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="textlabellocation",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="treenode",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="treenodeclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="treenodeconnector",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="treenodeconnectoredge",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="treenodeedge",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="userprofile",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="userprojecttoken",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="volume",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
            migrations.AlterField(
                model_name="volumeclassinstance",
                name="id",
                field=models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            migrations.AlterField(
                model_name="writablestack",
                name="id",
                field=models.AutoField(primary_key=True, serialize=False),
            ),
        ])
    ]
